config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :app do
    root to: 'app#index'
    get  "/*path" => "app#index"
    post "/*path" => "app#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/app/app_controller.rb
class App::AppController < ApplicationController
  layout 'app'

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/app/app/index.html.erb
<h1>APP</h1>

app/views/home/index.html.erb
<h1>Home#root</h1>
<%= link_to 'App', app_root_path %>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="referrer" content="same-origin"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'app' %>
  </head>
  <body class="body-app">
    <noscript>
      Please enable javascript to use this app
    </noscript>

    <div id="root"></div>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DefaultApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>